In [6]:
import torch   #查看torch版本
print(torch.__version__)  #注意是双下划线

import torchvision  #查看torchvision版本
print(torchvision.__version__)  #注意是双下划线

print(torch.version.cuda)  #注意是双下划线

print(torch.cuda.is_available())#如果cuda可用，则返回True

2.0.1
0.15.2
11.7
True


In [5]:
import dgl
import torch as th
# 边 0->1, 0->2, 0->3, 1->3
u, v = th.tensor([0, 0, 0, 1]), th.tensor([1, 2, 3, 3])
g = dgl.graph((u, v))
print(g) # 图中节点的数量是DGL通过给定的图的边列表中最大的点ID推断所得出的
# 获取节点的ID
print(g.nodes())
# 获取边的对应端点
print(g.edges())
# 获取边的对应端点和边ID
print(g.edges(form='all'))

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})
tensor([0, 1, 2, 3])
(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))
(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))


In [2]:
conda install -c dglteam/label/cu117 dgl

Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\yuki_younai\.conda\envs\PyTorch

  added / updated specs:
    - dgl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    appdirs-1.4.4              |     pyhd3eb1b0_0          12 KB  defaults
    dgl-1.1.0.cu117            |           py38_0        61.4 MB  dglteam/label/cu117
    icc_rt-2022.1.0            |       h6049295_2         6.5 MB  defaults
    pooch-1.4.0                |     pyhd3eb1b0_0          41 KB  defaults
    scipy-1.10.1               |   py38hdcfc7df_1        18.7 MB  defaults
    tqdm-4.65.0                |   py38hd4e2768_0         149 KB  defaults
    ------------------------------------------------------------
                                           Total:        86.8 MB

The following NEW packages will be INSTALLED:

  appdirs            anaconda/pkgs/main/noarch::appdi

In [76]:
import numpy as np

batch_size=32
neighbor_size=40
num=20
neighbor=torch.randint(neighbor_size,[1,1])
for i in range(batch_size):
    item_select=torch.randint(neighbor_size,[1,1])
    while item_select.shape[1]<20:
        item=torch.randint(neighbor_size,[1,1])
        while item in item_select:
            item=torch.randint(neighbor_size,[1,1])
        item_select=torch.cat([item_select,item],dim=1)
    neighbor=torch.cat([neighbor,item_select],dim=0)

    

TypeError: randint() received an invalid combination of arguments - got (int, list, type=type), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)


In [77]:
int(torch.randint(neighbor_size,[1,1]))

9

In [69]:
item

tensor([[27]])

In [63]:
import numpy as np
np.random.randint(30,[1])

ValueError: low >= high

In [57]:
item

tensor([[2]])

In [34]:
a=torch.tensor(31)
a

tensor(31)

In [35]:
a in item_select

True